Repository UBC-MDS/pylaundry, pull requests merged in 2020-03, with the labels that each got.

#36 transform_function's first draft
  poetry.lock
  pylaundry/transform_columns.py
  pyproject.toml
  tests/test_transform_columns.py
Labels: enhancement, group

#34 Adding fill_missing function draft and test cases
  pylaundry/fill_missing.py
  pyproject.toml
  tests/test_fill_missing.py
Labels: enhancement

#45 test suite with 100% coverage
  pylaundry/transform_columns.py
  tests/test_transform_columns.py
Labels: enhancement, individual

#47 removed incorrect url from readme
  README.md
Labels: documentation, enhancement

#55 pep8 style implemented for column transformer
  poetry.lock
  pylaundry/transform_columns.py
  pyproject.toml
  tests/test_transform_columns.py
Labels: enhancement, group

#57 added changed toml file
  pyproject.toml
Labels: enhancement

#74 added integration tests in test_integration()
  pylaundry/fill_missing.py
  tests/test_integration.py
Labels: enhancement

#97 added examples for transform function
  pylaundry/transform_columns.py
Labels: enhancement
